const path = require('node:path');
let browserTools;
try { browserTools = require('playwright'); }
catch { browserTools = require(path.join(path.dirname(process.execPath),'..','node_modules','playwright')); }
const { chromium } = browserTools;
const fs = require('node:fs');
const assert = require('node:assert/strict');
(async () => {
  fs.mkdirSync('.checks', {recursive:true});
  const browser = await chromium.launch({headless: true, channel: 'msedge'});
  let page = await browser.newPage({viewport:{width:1600,height:1050},deviceScaleFactor:1});
  const errors=[];
  page.on('pageerror', e => errors.push(e.message));
  await page.addInitScript(() => {
    Object.defineProperty(navigator,'share',{configurable:true,value:async data=>localStorage.setItem('share-test',JSON.stringify(data))});
  });
  await page.goto('http://localhost:4322/',{waitUntil:'domcontentloaded'});
  await page.locator('.post-list').waitFor();
  await page.evaluate(()=>document.fonts.ready);
  assert((await page.locator('body').evaluate(e=>getComputedStyle(e).fontFamily)).includes('LXGW WenKai'),'LXGW WenKai not applied');
  assert.equal(await page.locator('.page-footer .sitemap-group').count(),4,'Footer sitemap groups missing');
  assert.equal(await page.locator('#busuanzi_site_pv').count(),1,'Visitor counter missing');
  assert.equal(await page.locator('.l_left a.social[href="https://github.com/RayhanLynn"]').count(),1,'GitHub sidebar link missing');
  assert(Number(await page.locator('#site-runtime-days').textContent())>=1,'Runtime days missing');
  await page.screenshot({path:'.checks/home-desktop.png',fullPage:true});
  await page.locator('.page-footer').screenshot({path:'.checks/footer-desktop.png'});
  console.log('HOME', await page.title(), 'FONT', await page.locator('body').evaluate(e=>getComputedStyle(e).fontFamily));
  await page.locator('#search-input').fill('物理层');
  await page.locator('#search-result a[href*="physical-layer"]').first().waitFor({timeout:10000});
  console.log('SEARCH: chapter result found');
  await page.locator('.thought-link[href="/moments/#moment-2026-09-16"]').click();
  await page.waitForURL('**/moments/#moment-2026-09-16');
  assert(await page.locator('#moment-2026-09-16').isVisible(),'Linked moment is not visible');
  await page.locator('.moments-grid .moment-card').first().waitFor();
  assert.equal(await page.locator('.moment-card').count(),3,'Moment cards missing');
  assert.equal(await page.locator('.moment-photo').count(),2,'Moment photos missing');
  const like = page.locator('[data-like-id="moment-2026-09-16"]');
  await like.click();
  assert.equal(await like.getAttribute('aria-pressed'),'true','Moment like did not activate');
  assert.equal(await like.locator('span').textContent(),'1','Moment like count did not update');
  await page.reload({waitUntil:'domcontentloaded'});
  assert.equal(await page.locator('[data-like-id="moment-2026-09-16"]').getAttribute('aria-pressed'),'true','Moment like did not persist');
  await page.evaluate(()=>localStorage.removeItem('luckylotus-like:moment-2026-09-16'));
  assert.equal(await page.locator('#comments #giscus[data-repo-id="R_kgDOUearhA"]').count(),1,'Giscus container missing');
  await page.locator('#moment-2026-09-16 [data-share]').click();
  const shared=JSON.parse(await page.evaluate(()=>localStorage.getItem('share-test')));
  assert(shared.url.endsWith('/moments/#moment-2026-09-16'),'Share URL does not target the selected moment');
  assert.equal(await page.locator('#moment-2026-09-16 [data-share]').textContent(),'✓ 已分享','Share feedback missing');
  await page.screenshot({path:'.checks/moments-desktop.png',fullPage:true});
  console.log('MOMENTS: sidebar link, anchors, cards and photos found');
  await page.goto('http://localhost:4322/about/',{waitUntil:'domcontentloaded'});
  await page.locator('.article.banner .bg').waitFor();
  await page.screenshot({path:'.checks/about-desktop.png',fullPage:true});
  console.log('ABOUT: page banner found');
  await page.goto('http://localhost:4322/wiki/networks/physical-layer/',{waitUntil:'domcontentloaded'});
  await page.evaluate(()=>document.fonts.ready);
  await page.screenshot({path:'.checks/chapter-desktop.png',fullPage:true});
  console.log('CHAPTER', await page.locator('.katex').count(), 'math expressions');
  await page.locator('.toc a').filter({hasText:'编码的意义'}).first().click();
  assert(decodeURIComponent(new URL(page.url()).hash).includes('编码的意义'));
  await page.evaluate(()=>scrollTo(0,0));
  page = await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,reducedMotion:'reduce'});
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('http://localhost:4322/wiki/networks/physical-layer/',{waitUntil:'domcontentloaded'});
  await page.locator('article.content').waitFor();
  await page.screenshot({path:'.checks/chapter-mobile.png',fullPage:true});
  console.log('MOBILE',await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth})));
  await page.locator('button.leftbar-toggle').click();
  await page.locator('.l_left a[href="/wiki/networks/data-link-crc/"]').first().click();
  await page.waitForURL('**/wiki/networks/data-link-crc/');
  console.log('MOBILE MENU: chapter navigation passed');
  console.log('JS ERRORS',errors);
  assert.equal(errors.length,0,'Browser errors');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
